[package]
name = "aoc-2021-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"

[[bin]]
name = "aoc-2021-rust"
path = "src/rust/main.rs"